'\" t
.\"     Title: ccr-tools
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/29/2012
.\"    Manual: ccr-tools Manual
.\"    Source: ccr-tools
.\"  Language: English
.\"
.TH "ccr-tools" "8" "04/29/2012" "ccr-tools" "ccr-tools Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccr-tools \- Short description here
.SH "SYNOPSIS"
.sp
\fIccr-tools\fR [options] [packages]
.SH "DESCRIPTION"
.sp
Longer description here - note that all periods must look like this\&. 
.SH "OPTIONS"

.PP
\fB\--vote\fR <package-name>, \fB\-v\fR <package-name>
.RS 4
Vote for a package or packages in CCR\&.
.RE

.PP
\fB\--maintainer\fR <maintainer-username>, \fB\-m\fR <maintainer-username>
.RS 4
Search for all packages owned by a CCR user\&.
.RE


.PP
.SH "EXAMPLE USAGE"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Description of what the command below does: 
ccr-tools \-\-someoption stuff
.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Description of another command: 
ccr-tools \-something blah
.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Same thing, as many times as you want: 
ccr-tools \-other
.RE


.sp
.SH "CONFIGURATION"
.sp
Configuration information here. For example, where are the conf files, what options are valid in them, etc.
.sp


.SH "REPORTING BUGS"
.sp
Please report bugs at: <https://github.com/ccr-tools/ccr-tools/issues/>


.SH "AUTHORS"
.sp
Ram-Z and the other members of the ccr-tools team (https://github.com/ccr-tools/)